/*
 * Copyright (c) 2018 Goldfin.io. All Rights Reserved.
 */
import { Injectable } from '@angular/core';

export class HostPrice {
  vendor: string;
  name: string;
  type: string;
  cpu_type: string;
  cores: number;
  threads: number;
  sockets: number;
  ram_gb: number;
  hdd_storage_gb: number;
  ssd_storage_gb: number;
  other_storage_gb: number;
  other_storage_type: string;
  raid: boolean;
  bandwidth_gbps: number;
  region: string;
  datacenter: string;
  setup_cost: number;
  incremental_cost: number;
  increment_type: string;
  currency: string;
  effective_date: string;
}

const HOST_PRICES: HostPrice[] = [
  {
    vendor: "OVH.com",
    name: "SP-32",
    type: "DEDICATED",
    cpu_type: "Intel Xeon E3-1270v6",
    cores: 4,
    threads: 8,
    sockets: 1,
    ram_gb: 32,
    hdd_storage_gb: 2048,
    ssd_storage_gb: 0,
    other_storage_gb: 0,
    other_storage_type: "None",
    raid: true,
    bandwidth_gbps: .5,
    region: "EU",
    datacenter: "Gravelines",
    setup_cost: 0,
    incremental_cost: 107.99,
    increment_type: "Month",
    currency: "USD",
    effective_date: "2018-02-04"
  },
  {
    vendor: "OVH.com",
    name: "SP-32",
    type: "DEDICATED",
    cpu_type: "Intel Xeon E3-1270v6",
    cores: 4,
    threads: 8,
    sockets: 1,
    ram_gb: 32,
    hdd_storage_gb: 0,
    ssd_storage_gb: 480,
    other_storage_gb: 0,
    other_storage_type: "None",
    raid: true,
    bandwidth_gbps: .5,
    region: "EU",
    datacenter: "Gravelines",
    setup_cost: 0,
    incremental_cost: 123.99,
    increment_type: "Month",
    currency: "USD",
    effective_date: "2018-02-04",
  }, 
  {
    vendor: "OVH.com",
    name: "SP-64",
    type: "DEDICATED",
    cpu_type: "Intel Xeon E3-1270v6",
    cores: 4,
    threads: 8,
    sockets: 1,
    ram_gb: 64,
    hdd_storage_gb: 2048,
    ssd_storage_gb: 480,
    other_storage_gb: 0,
    other_storage_type: "None",
    raid: true,
    bandwidth_gbps: .5,
    region: "EU",
    datacenter: "Beauharnois",
    setup_cost: 0,
    incremental_cost: 211.99,
    increment_type: "Month",
    currency: "USD",
    effective_date: "2018-02-04",
  }, 
  {
    vendor: "OVH.com",
    name: "SP-64",
    type: "DEDICATED",
    cpu_type: "Intel Xeon E3-1270v6",
    cores: 4,
    threads: 8,
    sockets: 1,
    ram_gb: 64,
    hdd_storage_gb: 0,
    ssd_storage_gb: 450,
    other_storage_gb: 0,
    other_storage_type: "None",
    raid: true,
    bandwidth_gbps: .5,
    region: "EU",
    datacenter: "Beauharnois",
    setup_cost: 0,
    incremental_cost: 158.99,
    increment_type: "Month",
    currency: "USD",
    effective_date: "2018-02-04",
  },
  {
    vendor: "Azure",
    name: "D4 v3",
    type: "CLOUD",
    cpu_type: "Intel Xeon E5-2673v4",
    cores: 4,
    threads: -1,
    sockets: 1,
    ram_gb: 16,
    hdd_storage_gb: 100,
    ssd_storage_gb: 0,
    other_storage_gb: 0,
    other_storage_type: "None",
    raid: false,
    bandwidth_gbps: -1,
    region: "US",
    datacenter: "West US",
    setup_cost: 0,
    incremental_cost: 152.57,
    increment_type: "Month",
    currency: "USD",
    effective_date: "2018-02-04",
  },
  {
    vendor: "Azure",
    name: "D8 v3",
    type: "CLOUD",
    cpu_type: "Intel Xeon E5-2673v4",
    cores: 8,
    threads: -1,
    sockets: 1,
    ram_gb: 16,
    hdd_storage_gb: 200,
    ssd_storage_gb: 0,
    other_storage_gb: 0,
    other_storage_type: "None",
    raid: false,
    bandwidth_gbps: -1,
    region: "US",
    datacenter: "West US",
    setup_cost: 0,
    incremental_cost: 305.14,
    increment_type: "Month",
    currency: "USD",
    effective_date: "2018-02-04",
  },
  {
    vendor: "Azure",
    name: "D16 v3",
    type: "CLOUD",
    cpu_type: "Intel Xeon E5-2673v4",
    cores: 16,
    threads: -1,
    sockets: 1,
    ram_gb: 32,
    hdd_storage_gb: 400,
    ssd_storage_gb: 0,
    other_storage_gb: 0,
    other_storage_type: "None",
    raid: false,
    bandwidth_gbps: -1,
    region: "US",
    datacenter: "West US",
    setup_cost: 0,
    incremental_cost: 1220.56,
    increment_type: "Month",
    currency: "USD",
    effective_date: "2018-02-04",
  },
  {
    vendor: "AWS",
    name: "m5.large",
    type: "CLOUD",
    cpu_type: "Unknown",
    cores: -1,
    threads: 4,
    sockets: 1,
    ram_gb: 15,
    hdd_storage_gb: 0,
    ssd_storage_gb: 0,
    other_storage_gb: 0,
    other_storage_type: "None",
    raid: false,
    bandwidth_gbps: -1,
    region: "US",
    datacenter: "US West California",
    setup_cost: 0,
    incremental_cost: 0.224,
    increment_type: "Hour",
    currency: "USD",
    effective_date: "2018-02-04",
  },
  {
    vendor: "AWS",
    name: "m5.2xlarge",
    type: "CLOUD",
    cpu_type: "Unknown",
    cores: -1,
    threads: 8,
    sockets: 1,
    ram_gb: 31,
    hdd_storage_gb: 0,
    ssd_storage_gb: 0,
    other_storage_gb: 0,
    other_storage_type: "None",
    raid: false,
    bandwidth_gbps: -1,
    region: "US",
    datacenter: "US West California",
    setup_cost: 0,
    incremental_cost: 0.448,
    increment_type: "Hour",
    currency: "USD",
    effective_date: "2018-02-04",
  },
  {
    vendor: "AWS",
    name: "m5.2xlarge",
    type: "CLOUD",
    cpu_type: "Unknown",
    cores: -1,
    threads: 8,
    sockets: 1,
    ram_gb: 32,
    hdd_storage_gb: 0,
    ssd_storage_gb: 0,
    other_storage_gb: 0,
    other_storage_type: "None",
    raid: false,
    bandwidth_gbps: -1,
    region: "US",
    datacenter: "US East N. Virginia",
    setup_cost: 0,
    incremental_cost: 0.384,
    increment_type: "Hour",
    currency: "USD",
    effective_date: "2018-02-04",
  }
]

@Injectable()
export class HostPriceService {
  getHostPrices(): HostPrice[] {
    return HOST_PRICES;
  }
}
