# coding: utf-8

"""
    Goldfin Service API

    REST API for Goldfin Intelligent Invoice Processing

    OpenAPI spec version: 1.0.0
    Contact: info@goldfin.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ApiKey(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'user_id': 'str',
        'secret': 'str',
        'last_touched_date': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'user_id': 'userId',
        'secret': 'secret',
        'last_touched_date': 'lastTouchedDate'
    }

    def __init__(self, id=None, name=None, user_id=None, secret=None, last_touched_date=None):
        """
        ApiKey - a model defined in Swagger
        """

        self._id = None
        self._name = None
        self._user_id = None
        self._secret = None
        self._last_touched_date = None

        if id is not None:
          self.id = id
        if name is not None:
          self.name = name
        if user_id is not None:
          self.user_id = user_id
        if secret is not None:
          self.secret = secret
        if last_touched_date is not None:
          self.last_touched_date = last_touched_date

    @property
    def id(self):
        """
        Gets the id of this ApiKey.
        Unique API key ID

        :return: The id of this ApiKey.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ApiKey.
        Unique API key ID

        :param id: The id of this ApiKey.
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this ApiKey.
        Name of this API key; must be unique among keys owned by a user.

        :return: The name of this ApiKey.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ApiKey.
        Name of this API key; must be unique among keys owned by a user.

        :param name: The name of this ApiKey.
        :type: str
        """

        self._name = name

    @property
    def user_id(self):
        """
        Gets the user_id of this ApiKey.
        User ID

        :return: The user_id of this ApiKey.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """
        Sets the user_id of this ApiKey.
        User ID

        :param user_id: The user_id of this ApiKey.
        :type: str
        """

        self._user_id = user_id

    @property
    def secret(self):
        """
        Gets the secret of this ApiKey.
        Secret password for the API key. This is only shown on initial creation; if lost a new API key must be created to replace it.

        :return: The secret of this ApiKey.
        :rtype: str
        """
        return self._secret

    @secret.setter
    def secret(self, secret):
        """
        Sets the secret of this ApiKey.
        Secret password for the API key. This is only shown on initial creation; if lost a new API key must be created to replace it.

        :param secret: The secret of this ApiKey.
        :type: str
        """

        self._secret = secret

    @property
    def last_touched_date(self):
        """
        Gets the last_touched_date of this ApiKey.
        Date of last use of key

        :return: The last_touched_date of this ApiKey.
        :rtype: datetime
        """
        return self._last_touched_date

    @last_touched_date.setter
    def last_touched_date(self, last_touched_date):
        """
        Sets the last_touched_date of this ApiKey.
        Date of last use of key

        :param last_touched_date: The last_touched_date of this ApiKey.
        :type: datetime
        """

        self._last_touched_date = last_touched_date

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ApiKey):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
