# coding: utf-8

"""
    Goldfin Service API

    REST API for Goldfin Intelligent Invoice Processing

    OpenAPI spec version: 1.0.0
    Contact: info@goldfin.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Host(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'host_id': 'str',
        'resource_id': 'str',
        'effective_date': 'datetime',
        'vendor_identifier': 'str',
        'data_series_id': 'str',
        'host_type': 'str',
        'host_model': 'str',
        'region': 'str',
        'zone': 'str',
        'datacenter': 'str',
        'cpu': 'str',
        'socket_count': 'int',
        'core_count': 'int',
        'thread_count': 'int',
        'ram': 'int',
        'hdd': 'int',
        'ssd': 'int',
        'nic_count': 'int',
        'network_traffic_limit': 'int',
        'backup_enabled': 'bool',
        'tags': 'TagSet'
    }

    attribute_map = {
        'id': 'id',
        'host_id': 'hostId',
        'resource_id': 'resourceId',
        'effective_date': 'effectiveDate',
        'vendor_identifier': 'vendorIdentifier',
        'data_series_id': 'dataSeriesId',
        'host_type': 'hostType',
        'host_model': 'hostModel',
        'region': 'region',
        'zone': 'zone',
        'datacenter': 'datacenter',
        'cpu': 'cpu',
        'socket_count': 'socketCount',
        'core_count': 'coreCount',
        'thread_count': 'threadCount',
        'ram': 'ram',
        'hdd': 'hdd',
        'ssd': 'ssd',
        'nic_count': 'nicCount',
        'network_traffic_limit': 'networkTrafficLimit',
        'backup_enabled': 'backupEnabled',
        'tags': 'tags'
    }

    def __init__(self, id=None, host_id=None, resource_id=None, effective_date=None, vendor_identifier=None, data_series_id=None, host_type=None, host_model=None, region=None, zone=None, datacenter=None, cpu=None, socket_count=None, core_count=None, thread_count=None, ram=None, hdd=None, ssd=None, nic_count=None, network_traffic_limit=None, backup_enabled=None, tags=None):
        """
        Host - a model defined in Swagger
        """

        self._id = None
        self._host_id = None
        self._resource_id = None
        self._effective_date = None
        self._vendor_identifier = None
        self._data_series_id = None
        self._host_type = None
        self._host_model = None
        self._region = None
        self._zone = None
        self._datacenter = None
        self._cpu = None
        self._socket_count = None
        self._core_count = None
        self._thread_count = None
        self._ram = None
        self._hdd = None
        self._ssd = None
        self._nic_count = None
        self._network_traffic_limit = None
        self._backup_enabled = None
        self._tags = None

        if id is not None:
          self.id = id
        if host_id is not None:
          self.host_id = host_id
        if resource_id is not None:
          self.resource_id = resource_id
        if effective_date is not None:
          self.effective_date = effective_date
        if vendor_identifier is not None:
          self.vendor_identifier = vendor_identifier
        if data_series_id is not None:
          self.data_series_id = data_series_id
        if host_type is not None:
          self.host_type = host_type
        if host_model is not None:
          self.host_model = host_model
        if region is not None:
          self.region = region
        if zone is not None:
          self.zone = zone
        if datacenter is not None:
          self.datacenter = datacenter
        if cpu is not None:
          self.cpu = cpu
        if socket_count is not None:
          self.socket_count = socket_count
        if core_count is not None:
          self.core_count = core_count
        if thread_count is not None:
          self.thread_count = thread_count
        if ram is not None:
          self.ram = ram
        if hdd is not None:
          self.hdd = hdd
        if ssd is not None:
          self.ssd = ssd
        if nic_count is not None:
          self.nic_count = nic_count
        if network_traffic_limit is not None:
          self.network_traffic_limit = network_traffic_limit
        if backup_enabled is not None:
          self.backup_enabled = backup_enabled
        if tags is not None:
          self.tags = tags

    @property
    def id(self):
        """
        Gets the id of this Host.
        Host record ID

        :return: The id of this Host.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Host.
        Host record ID

        :param id: The id of this Host.
        :type: str
        """

        self._id = id

    @property
    def host_id(self):
        """
        Gets the host_id of this Host.
        Internal host ID from vendor used to identify host in inventory

        :return: The host_id of this Host.
        :rtype: str
        """
        return self._host_id

    @host_id.setter
    def host_id(self, host_id):
        """
        Sets the host_id of this Host.
        Internal host ID from vendor used to identify host in inventory

        :param host_id: The host_id of this Host.
        :type: str
        """

        self._host_id = host_id

    @property
    def resource_id(self):
        """
        Gets the resource_id of this Host.
        Inventory resource ID that can be related to invoice item resource ID

        :return: The resource_id of this Host.
        :rtype: str
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id):
        """
        Sets the resource_id of this Host.
        Inventory resource ID that can be related to invoice item resource ID

        :param resource_id: The resource_id of this Host.
        :type: str
        """

        self._resource_id = resource_id

    @property
    def effective_date(self):
        """
        Gets the effective_date of this Host.
        Observation effective date

        :return: The effective_date of this Host.
        :rtype: datetime
        """
        return self._effective_date

    @effective_date.setter
    def effective_date(self, effective_date):
        """
        Sets the effective_date of this Host.
        Observation effective date

        :param effective_date: The effective_date of this Host.
        :type: datetime
        """

        self._effective_date = effective_date

    @property
    def vendor_identifier(self):
        """
        Gets the vendor_identifier of this Host.
        Vendor identifier key

        :return: The vendor_identifier of this Host.
        :rtype: str
        """
        return self._vendor_identifier

    @vendor_identifier.setter
    def vendor_identifier(self, vendor_identifier):
        """
        Sets the vendor_identifier of this Host.
        Vendor identifier key

        :param vendor_identifier: The vendor_identifier of this Host.
        :type: str
        """

        self._vendor_identifier = vendor_identifier

    @property
    def data_series_id(self):
        """
        Gets the data_series_id of this Host.
        Id of data series from which this host record was derived

        :return: The data_series_id of this Host.
        :rtype: str
        """
        return self._data_series_id

    @data_series_id.setter
    def data_series_id(self, data_series_id):
        """
        Sets the data_series_id of this Host.
        Id of data series from which this host record was derived

        :param data_series_id: The data_series_id of this Host.
        :type: str
        """

        self._data_series_id = data_series_id

    @property
    def host_type(self):
        """
        Gets the host_type of this Host.
        Type of host

        :return: The host_type of this Host.
        :rtype: str
        """
        return self._host_type

    @host_type.setter
    def host_type(self, host_type):
        """
        Sets the host_type of this Host.
        Type of host

        :param host_type: The host_type of this Host.
        :type: str
        """
        allowed_values = ["BARE_METAL", "CLOUD", "UNKNOWN"]
        if host_type not in allowed_values:
            raise ValueError(
                "Invalid value for `host_type` ({0}), must be one of {1}"
                .format(host_type, allowed_values)
            )

        self._host_type = host_type

    @property
    def host_model(self):
        """
        Gets the host_model of this Host.
        Host model or marketing name

        :return: The host_model of this Host.
        :rtype: str
        """
        return self._host_model

    @host_model.setter
    def host_model(self, host_model):
        """
        Sets the host_model of this Host.
        Host model or marketing name

        :param host_model: The host_model of this Host.
        :type: str
        """

        self._host_model = host_model

    @property
    def region(self):
        """
        Gets the region of this Host.
        Geographic region

        :return: The region of this Host.
        :rtype: str
        """
        return self._region

    @region.setter
    def region(self, region):
        """
        Sets the region of this Host.
        Geographic region

        :param region: The region of this Host.
        :type: str
        """

        self._region = region

    @property
    def zone(self):
        """
        Gets the zone of this Host.
        Availability zone

        :return: The zone of this Host.
        :rtype: str
        """
        return self._zone

    @zone.setter
    def zone(self, zone):
        """
        Sets the zone of this Host.
        Availability zone

        :param zone: The zone of this Host.
        :type: str
        """

        self._zone = zone

    @property
    def datacenter(self):
        """
        Gets the datacenter of this Host.
        Data center

        :return: The datacenter of this Host.
        :rtype: str
        """
        return self._datacenter

    @datacenter.setter
    def datacenter(self, datacenter):
        """
        Sets the datacenter of this Host.
        Data center

        :param datacenter: The datacenter of this Host.
        :type: str
        """

        self._datacenter = datacenter

    @property
    def cpu(self):
        """
        Gets the cpu of this Host.
        CPU model

        :return: The cpu of this Host.
        :rtype: str
        """
        return self._cpu

    @cpu.setter
    def cpu(self, cpu):
        """
        Sets the cpu of this Host.
        CPU model

        :param cpu: The cpu of this Host.
        :type: str
        """

        self._cpu = cpu

    @property
    def socket_count(self):
        """
        Gets the socket_count of this Host.
        Number of CPU sockets

        :return: The socket_count of this Host.
        :rtype: int
        """
        return self._socket_count

    @socket_count.setter
    def socket_count(self, socket_count):
        """
        Sets the socket_count of this Host.
        Number of CPU sockets

        :param socket_count: The socket_count of this Host.
        :type: int
        """

        self._socket_count = socket_count

    @property
    def core_count(self):
        """
        Gets the core_count of this Host.
        Number of cores per socket

        :return: The core_count of this Host.
        :rtype: int
        """
        return self._core_count

    @core_count.setter
    def core_count(self, core_count):
        """
        Sets the core_count of this Host.
        Number of cores per socket

        :param core_count: The core_count of this Host.
        :type: int
        """

        self._core_count = core_count

    @property
    def thread_count(self):
        """
        Gets the thread_count of this Host.
        Number of hardware threads per core

        :return: The thread_count of this Host.
        :rtype: int
        """
        return self._thread_count

    @thread_count.setter
    def thread_count(self, thread_count):
        """
        Sets the thread_count of this Host.
        Number of hardware threads per core

        :param thread_count: The thread_count of this Host.
        :type: int
        """

        self._thread_count = thread_count

    @property
    def ram(self):
        """
        Gets the ram of this Host.
        Size of RAM in bytes

        :return: The ram of this Host.
        :rtype: int
        """
        return self._ram

    @ram.setter
    def ram(self, ram):
        """
        Sets the ram of this Host.
        Size of RAM in bytes

        :param ram: The ram of this Host.
        :type: int
        """

        self._ram = ram

    @property
    def hdd(self):
        """
        Gets the hdd of this Host.
        Size of HDD storage in bytes

        :return: The hdd of this Host.
        :rtype: int
        """
        return self._hdd

    @hdd.setter
    def hdd(self, hdd):
        """
        Sets the hdd of this Host.
        Size of HDD storage in bytes

        :param hdd: The hdd of this Host.
        :type: int
        """

        self._hdd = hdd

    @property
    def ssd(self):
        """
        Gets the ssd of this Host.
        Size of SSD storage in bytes

        :return: The ssd of this Host.
        :rtype: int
        """
        return self._ssd

    @ssd.setter
    def ssd(self, ssd):
        """
        Sets the ssd of this Host.
        Size of SSD storage in bytes

        :param ssd: The ssd of this Host.
        :type: int
        """

        self._ssd = ssd

    @property
    def nic_count(self):
        """
        Gets the nic_count of this Host.
        Number of network interface cards (NICs)

        :return: The nic_count of this Host.
        :rtype: int
        """
        return self._nic_count

    @nic_count.setter
    def nic_count(self, nic_count):
        """
        Sets the nic_count of this Host.
        Number of network interface cards (NICs)

        :param nic_count: The nic_count of this Host.
        :type: int
        """

        self._nic_count = nic_count

    @property
    def network_traffic_limit(self):
        """
        Gets the network_traffic_limit of this Host.
        Number of bytes of network traffer per billing period if there is a hard limit

        :return: The network_traffic_limit of this Host.
        :rtype: int
        """
        return self._network_traffic_limit

    @network_traffic_limit.setter
    def network_traffic_limit(self, network_traffic_limit):
        """
        Sets the network_traffic_limit of this Host.
        Number of bytes of network traffer per billing period if there is a hard limit

        :param network_traffic_limit: The network_traffic_limit of this Host.
        :type: int
        """

        self._network_traffic_limit = network_traffic_limit

    @property
    def backup_enabled(self):
        """
        Gets the backup_enabled of this Host.
        If true backup is enabled for this host

        :return: The backup_enabled of this Host.
        :rtype: bool
        """
        return self._backup_enabled

    @backup_enabled.setter
    def backup_enabled(self, backup_enabled):
        """
        Sets the backup_enabled of this Host.
        If true backup is enabled for this host

        :param backup_enabled: The backup_enabled of this Host.
        :type: bool
        """

        self._backup_enabled = backup_enabled

    @property
    def tags(self):
        """
        Gets the tags of this Host.

        :return: The tags of this Host.
        :rtype: TagSet
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """
        Sets the tags of this Host.

        :param tags: The tags of this Host.
        :type: TagSet
        """

        self._tags = tags

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Host):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
