# Dockerfile for OCR service
# Use latest xenial (16.04) as base.
FROM ubuntu:xenial-20180808
RUN apt-get update -y
RUN apt-get install -y python3-pip python3-dev
COPY . /ocr
WORKDIR /ocr
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
RUN python3 setup.py install
ENTRYPOINT ["/ocr/bin/datactl-wrapper", "--daemon", "--log-level=INFO", "--log-file=/var/log/goldfin/data.log"]
