# coding: utf-8

"""
    Goldfin Intelligent Invoice API

    Public REST API for managing IT service invoices and inventory

    OpenAPI spec version: 1.0.0
    Contact: rhodges@skylineresearch.comm
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import sys
from setuptools import setup, find_packages

NAME = ""
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Goldfin Intelligent Invoice API",
    author_email="rhodges@skylineresearch.comm",
    url="",
    keywords=["Swagger", "Goldfin Intelligent Invoice API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Public REST API for managing IT service invoices and inventory
    """
)
