# coding: utf-8

"""
    Goldfin Service API

    REST API for Goldfin Intelligent Invoice Processing

    OpenAPI spec version: 1.0.0
    Contact: info@goldfin.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import api
from api.rest import ApiException
from api.apis.extract_api import ExtractApi


class TestExtractApi(unittest.TestCase):
    """ ExtractApi unit test stubs """

    def setUp(self):
        self.api = api.apis.extract_api.ExtractApi()

    def tearDown(self):
        pass

    def test_extract_download(self):
        """
        Test case for extract_download

        Download a data extract
        """
        pass

    def test_extract_types(self):
        """
        Test case for extract_types

        List available extract types
        """
        pass


if __name__ == '__main__':
    unittest.main()
