# coding: utf-8

"""
    Goldfin Service API

    REST API for Goldfin Intelligent Invoice Processing

    OpenAPI spec version: 1.0.0
    Contact: info@goldfin.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import api
from api.rest import ApiException
from api.apis.tenant_api import TenantApi


class TestTenantApi(unittest.TestCase):
    """ TenantApi unit test stubs """

    def setUp(self):
        self.api = api.apis.tenant_api.TenantApi()

    def tearDown(self):
        pass

    def test_tenant_create(self):
        """
        Test case for tenant_create

        Create a new tenant
        """
        pass

    def test_tenant_delete(self):
        """
        Test case for tenant_delete

        Delete a tenant
        """
        pass

    def test_tenant_show(self):
        """
        Test case for tenant_show

        Show a single tenant
        """
        pass

    def test_tenant_showall(self):
        """
        Test case for tenant_showall

        List tenants
        """
        pass

    def test_tenant_update(self):
        """
        Test case for tenant_update

        Update a tenant
        """
        pass

    def test_user_create(self):
        """
        Test case for user_create

        Create a new user for a tenant
        """
        pass

    def test_user_delete(self):
        """
        Test case for user_delete

        Delete a user
        """
        pass

    def test_user_show(self):
        """
        Test case for user_show

        Show a single user
        """
        pass

    def test_user_showall(self):
        """
        Test case for user_showall

        List users
        """
        pass

    def test_user_update(self):
        """
        Test case for user_update

        Update a user
        """
        pass

    def test_user_update_password(self):
        """
        Test case for user_update_password

        Update user password
        """
        pass


if __name__ == '__main__':
    unittest.main()
