# coding: utf-8

"""
    Goldfin Service API

    REST API for Goldfin Intelligent Invoice Processing

    OpenAPI spec version: 1.0.0
    Contact: info@goldfin.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import api
from api.rest import ApiException
from api.apis.vendor_api import VendorApi


class TestVendorApi(unittest.TestCase):
    """ VendorApi unit test stubs """

    def setUp(self):
        self.api = api.apis.vendor_api.VendorApi()

    def tearDown(self):
        pass

    def test_vendor_create(self):
        """
        Test case for vendor_create

        Create a new vendor
        """
        pass

    def test_vendor_delete(self):
        """
        Test case for vendor_delete

        Delete a vendor
        """
        pass

    def test_vendor_show(self):
        """
        Test case for vendor_show

        Show a single vendor
        """
        pass

    def test_vendor_showall(self):
        """
        Test case for vendor_showall

        List vendors
        """
        pass

    def test_vendor_update(self):
        """
        Test case for vendor_update

        Update a vendor
        """
        pass


if __name__ == '__main__':
    unittest.main()
