# coding: utf-8

"""
    Goldfin Service API

    REST API for Goldfin Intelligent Invoice Processing

    OpenAPI spec version: 1.0.0
    Contact: info@goldfin.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import api
from api.rest import ApiException
from api.models.host import Host


class TestHost(unittest.TestCase):
    """ Host unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHost(self):
        """
        Test Host
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = api.models.host.Host()
        pass


if __name__ == '__main__':
    unittest.main()
