# coding: utf-8

"""
    Goldfin Service API

    REST API for Goldfin Intelligent Invoice Processing

    OpenAPI spec version: 1.0.0
    Contact: info@goldfin.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import api
from api.rest import ApiException
from api.apis.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """ UserApi unit test stubs """

    def setUp(self):
        self.api = api.apis.user_api.UserApi()

    def tearDown(self):
        pass

    def test_apikey_create(self):
        """
        Test case for apikey_create

        Create a new API key
        """
        pass

    def test_apikey_delete(self):
        """
        Test case for apikey_delete

        Delete an API key
        """
        pass

    def test_apikey_show_all(self):
        """
        Test case for apikey_show_all

        Return list of API keys
        """
        pass

    def test_user_create(self):
        """
        Test case for user_create

        Create a new user for a tenant
        """
        pass

    def test_user_delete(self):
        """
        Test case for user_delete

        Delete a user
        """
        pass

    def test_user_show(self):
        """
        Test case for user_show

        Show a single user
        """
        pass

    def test_user_showall(self):
        """
        Test case for user_showall

        List users
        """
        pass

    def test_user_update(self):
        """
        Test case for user_update

        Update a user
        """
        pass

    def test_user_update_password(self):
        """
        Test case for user_update_password

        Update user password
        """
        pass


if __name__ == '__main__':
    unittest.main()
