/**
 * Copyright (c) 2017 Goldfin.io.  All rights reserved. 
 */
package io.goldfin.shared.crypto.test;

import java.util.List;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import io.goldfin.shared.crypto.Randomizer;
import org.junit.Assert;

/**
 * Verify generation of random bytes.
 */
public class RandomDataTest {
	static final Logger logger = LoggerFactory.getLogger(RandomDataTest.class);

	/**
	 * Verify that random byte generation creates unique values for strings up to 20
	 * bytes.
	 */
	@Test
	public void testPasswordHashingAndValidation() throws Exception {
		Randomizer random = new Randomizer();
		logger.debug("Randomizer algorithm: " + random.getAlgorithm());

		for (int i = 8; i <= 10; i++) {
			Map<String, Boolean> map = new HashMap<String, Boolean>();
			List<String> list = new ArrayList<String>();
			for (int j = 0; j < 5; j++) {
				String randomValue = random.base64RandomBytes(i * 2);
				list.add(randomValue);
				map.put(randomValue, true);
				logger.debug(String.format("bytes: %d, string: %s", i * 2, randomValue));
			}
			Assert.assertEquals("Random string collision detected: " + list.toString(), list.size(), map.size());
		}
	}

	/**
	 * Verify that two different generators do not generate trivially generate the
	 * same values. This ensures we don't have a problem with generators starting
	 * from the same seed, which would be very bad.
	 */
	@Test
	public void testRandomizationBetweenGenerators() throws Exception {
		Randomizer random = new Randomizer();
		logger.debug("Randomizer algorithm: " + random.getAlgorithm());

		Randomizer r1 = new Randomizer();
		Randomizer r2 = new Randomizer();

		// Generate base values from r1.
		Map<String, Boolean> map = new HashMap<String, Boolean>();
		for (int i = 0; i < 10; i++) {
			String randomValue = r1.base64RandomBytes(20);
			map.put(randomValue, true);
			logger.debug(String.format("#1 random value: %s", randomValue));
		}

		// Now generate r2 values and ensure they are different from values of other
		// randomizer.
		for (int i = 0; i < 10; i++) {
			String randomValue = r2.base64RandomBytes(20);
			logger.debug(String.format("#2 random value: %s", randomValue));
			if (map.containsKey(randomValue)) {
				throw new Exception("Same value generated by two randomizers: " + randomValue);
			}
		}
	}

}