# Compose file for full Goldfin system.
version: '3.6'
services:
   api:
       image: goldfin/admin-server:0.9.0
       network_mode: host
       volumes:
         - type: bind
           source: /home/rhodges/goldfin/conf
           target: /var/lib/goldfin/conf
       #ports:
       # - "443:8443"
   ocr:
       image: goldfin/scanctl:0.9.0
       volumes:
         - type: bind
           source: /home/rhodges/goldfin/conf
           target: /var/lib/goldfin/conf
   data:
       image: goldfin/datactl:0.9.0
       volumes:
         - type: bind
           source: /home/rhodges/goldfin/conf
           target: /var/lib/goldfin/conf
#   dbms:
#       image: postgres:10
#       environment:
#         - POSTGRES_PASSWORD=secret
#       ports:
#        - "15432:5432"
#       volumes:
#        - postgresql-10:/var/lib/mysql/data

volumes:
  postgresql-10:
