# coding: utf-8

"""
    Goldfin Service API

    REST API for Goldfin Intelligent Invoice Processing

    OpenAPI spec version: 1.0.0
    Contact: info@goldfin.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InvoiceItem(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'rid': 'int',
        'parent_rid': 'int',
        'item_row_type': 'str',
        'item_id': 'str',
        'resource_id': 'str',
        'description': 'str',
        'unit_amount': 'float',
        'units': 'int',
        'unit_type': 'str',
        'subtotal_amount': 'float',
        'credit': 'float',
        'tax': 'float',
        'total_amount': 'float',
        'currency': 'str',
        'start_date': 'datetime',
        'end_date': 'datetime',
        'charge_type': 'str',
        'region': 'DocumentRegion',
        'inventory_id': 'str',
        'inventory_type': 'str',
        'tags': 'TagSet'
    }

    attribute_map = {
        'rid': 'rid',
        'parent_rid': 'parentRid',
        'item_row_type': 'itemRowType',
        'item_id': 'itemId',
        'resource_id': 'resourceId',
        'description': 'description',
        'unit_amount': 'unitAmount',
        'units': 'units',
        'unit_type': 'unitType',
        'subtotal_amount': 'subtotalAmount',
        'credit': 'credit',
        'tax': 'tax',
        'total_amount': 'totalAmount',
        'currency': 'currency',
        'start_date': 'startDate',
        'end_date': 'endDate',
        'charge_type': 'chargeType',
        'region': 'region',
        'inventory_id': 'inventoryId',
        'inventory_type': 'inventoryType',
        'tags': 'tags'
    }

    def __init__(self, rid=None, parent_rid=None, item_row_type=None, item_id=None, resource_id=None, description=None, unit_amount=None, units=None, unit_type=None, subtotal_amount=None, credit=None, tax=None, total_amount=None, currency=None, start_date=None, end_date=None, charge_type='RECURRING', region=None, inventory_id=None, inventory_type=None, tags=None):
        """
        InvoiceItem - a model defined in Swagger
        """

        self._rid = None
        self._parent_rid = None
        self._item_row_type = None
        self._item_id = None
        self._resource_id = None
        self._description = None
        self._unit_amount = None
        self._units = None
        self._unit_type = None
        self._subtotal_amount = None
        self._credit = None
        self._tax = None
        self._total_amount = None
        self._currency = None
        self._start_date = None
        self._end_date = None
        self._charge_type = None
        self._region = None
        self._inventory_id = None
        self._inventory_type = None
        self._tags = None

        if rid is not None:
          self.rid = rid
        if parent_rid is not None:
          self.parent_rid = parent_rid
        if item_row_type is not None:
          self.item_row_type = item_row_type
        if item_id is not None:
          self.item_id = item_id
        if resource_id is not None:
          self.resource_id = resource_id
        if description is not None:
          self.description = description
        if unit_amount is not None:
          self.unit_amount = unit_amount
        if units is not None:
          self.units = units
        if unit_type is not None:
          self.unit_type = unit_type
        if subtotal_amount is not None:
          self.subtotal_amount = subtotal_amount
        if credit is not None:
          self.credit = credit
        if tax is not None:
          self.tax = tax
        if total_amount is not None:
          self.total_amount = total_amount
        if currency is not None:
          self.currency = currency
        if start_date is not None:
          self.start_date = start_date
        if end_date is not None:
          self.end_date = end_date
        if charge_type is not None:
          self.charge_type = charge_type
        if region is not None:
          self.region = region
        if inventory_id is not None:
          self.inventory_id = inventory_id
        if inventory_type is not None:
          self.inventory_type = inventory_type
        if tags is not None:
          self.tags = tags

    @property
    def rid(self):
        """
        Gets the rid of this InvoiceItem.
        Row number of line item starting at 1.

        :return: The rid of this InvoiceItem.
        :rtype: int
        """
        return self._rid

    @rid.setter
    def rid(self, rid):
        """
        Sets the rid of this InvoiceItem.
        Row number of line item starting at 1.

        :param rid: The rid of this InvoiceItem.
        :type: int
        """

        self._rid = rid

    @property
    def parent_rid(self):
        """
        Gets the parent_rid of this InvoiceItem.
        Row ID of a summary invoice item to which this item belongs

        :return: The parent_rid of this InvoiceItem.
        :rtype: int
        """
        return self._parent_rid

    @parent_rid.setter
    def parent_rid(self, parent_rid):
        """
        Sets the parent_rid of this InvoiceItem.
        Row ID of a summary invoice item to which this item belongs

        :param parent_rid: The parent_rid of this InvoiceItem.
        :type: int
        """

        self._parent_rid = parent_rid

    @property
    def item_row_type(self):
        """
        Gets the item_row_type of this InvoiceItem.
        Type of invoice row item  * DETAIL - A payable item  * SUMMARY - A sub-total or total line 

        :return: The item_row_type of this InvoiceItem.
        :rtype: str
        """
        return self._item_row_type

    @item_row_type.setter
    def item_row_type(self, item_row_type):
        """
        Sets the item_row_type of this InvoiceItem.
        Type of invoice row item  * DETAIL - A payable item  * SUMMARY - A sub-total or total line 

        :param item_row_type: The item_row_type of this InvoiceItem.
        :type: str
        """
        allowed_values = ["DETAIL", "SUMMARY"]
        if item_row_type not in allowed_values:
            raise ValueError(
                "Invalid value for `item_row_type` ({0}), must be one of {1}"
                .format(item_row_type, allowed_values)
            )

        self._item_row_type = item_row_type

    @property
    def item_id(self):
        """
        Gets the item_id of this InvoiceItem.
        Invoice item ID if specified

        :return: The item_id of this InvoiceItem.
        :rtype: str
        """
        return self._item_id

    @item_id.setter
    def item_id(self, item_id):
        """
        Sets the item_id of this InvoiceItem.
        Invoice item ID if specified

        :param item_id: The item_id of this InvoiceItem.
        :type: str
        """

        self._item_id = item_id

    @property
    def resource_id(self):
        """
        Gets the resource_id of this InvoiceItem.
        Inventory resource ID

        :return: The resource_id of this InvoiceItem.
        :rtype: str
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id):
        """
        Sets the resource_id of this InvoiceItem.
        Inventory resource ID

        :param resource_id: The resource_id of this InvoiceItem.
        :type: str
        """

        self._resource_id = resource_id

    @property
    def description(self):
        """
        Gets the description of this InvoiceItem.
        Invoice item description

        :return: The description of this InvoiceItem.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this InvoiceItem.
        Invoice item description

        :param description: The description of this InvoiceItem.
        :type: str
        """

        self._description = description

    @property
    def unit_amount(self):
        """
        Gets the unit_amount of this InvoiceItem.
        Cost per unit

        :return: The unit_amount of this InvoiceItem.
        :rtype: float
        """
        return self._unit_amount

    @unit_amount.setter
    def unit_amount(self, unit_amount):
        """
        Sets the unit_amount of this InvoiceItem.
        Cost per unit

        :param unit_amount: The unit_amount of this InvoiceItem.
        :type: float
        """

        self._unit_amount = unit_amount

    @property
    def units(self):
        """
        Gets the units of this InvoiceItem.
        Number of units

        :return: The units of this InvoiceItem.
        :rtype: int
        """
        return self._units

    @units.setter
    def units(self, units):
        """
        Sets the units of this InvoiceItem.
        Number of units

        :param units: The units of this InvoiceItem.
        :type: int
        """

        self._units = units

    @property
    def unit_type(self):
        """
        Gets the unit_type of this InvoiceItem.
        Type of multiplier for computing invoice item total  * MONTH - Monthly subscription (may be prorated depending on vendor)  * HOUR - Hours in use  * USER - Number of users  * GB - Gigabytes (for example as a unit of storage or transfer)  * OTHER - Some other unit of consumption 

        :return: The unit_type of this InvoiceItem.
        :rtype: str
        """
        return self._unit_type

    @unit_type.setter
    def unit_type(self, unit_type):
        """
        Sets the unit_type of this InvoiceItem.
        Type of multiplier for computing invoice item total  * MONTH - Monthly subscription (may be prorated depending on vendor)  * HOUR - Hours in use  * USER - Number of users  * GB - Gigabytes (for example as a unit of storage or transfer)  * OTHER - Some other unit of consumption 

        :param unit_type: The unit_type of this InvoiceItem.
        :type: str
        """
        allowed_values = ["MONTH", "HOUR", "USER", "GB", "OTHER"]
        if unit_type not in allowed_values:
            raise ValueError(
                "Invalid value for `unit_type` ({0}), must be one of {1}"
                .format(unit_type, allowed_values)
            )

        self._unit_type = unit_type

    @property
    def subtotal_amount(self):
        """
        Gets the subtotal_amount of this InvoiceItem.
        Item cost for all units without credits or taxes

        :return: The subtotal_amount of this InvoiceItem.
        :rtype: float
        """
        return self._subtotal_amount

    @subtotal_amount.setter
    def subtotal_amount(self, subtotal_amount):
        """
        Sets the subtotal_amount of this InvoiceItem.
        Item cost for all units without credits or taxes

        :param subtotal_amount: The subtotal_amount of this InvoiceItem.
        :type: float
        """

        self._subtotal_amount = subtotal_amount

    @property
    def credit(self):
        """
        Gets the credit of this InvoiceItem.
        Credit applied to line item

        :return: The credit of this InvoiceItem.
        :rtype: float
        """
        return self._credit

    @credit.setter
    def credit(self, credit):
        """
        Sets the credit of this InvoiceItem.
        Credit applied to line item

        :param credit: The credit of this InvoiceItem.
        :type: float
        """

        self._credit = credit

    @property
    def tax(self):
        """
        Gets the tax of this InvoiceItem.
        Tax on line item

        :return: The tax of this InvoiceItem.
        :rtype: float
        """
        return self._tax

    @tax.setter
    def tax(self, tax):
        """
        Sets the tax of this InvoiceItem.
        Tax on line item

        :param tax: The tax of this InvoiceItem.
        :type: float
        """

        self._tax = tax

    @property
    def total_amount(self):
        """
        Gets the total_amount of this InvoiceItem.
        Total cost for all units including taxes and credits

        :return: The total_amount of this InvoiceItem.
        :rtype: float
        """
        return self._total_amount

    @total_amount.setter
    def total_amount(self, total_amount):
        """
        Sets the total_amount of this InvoiceItem.
        Total cost for all units including taxes and credits

        :param total_amount: The total_amount of this InvoiceItem.
        :type: float
        """

        self._total_amount = total_amount

    @property
    def currency(self):
        """
        Gets the currency of this InvoiceItem.
        Item currency

        :return: The currency of this InvoiceItem.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """
        Sets the currency of this InvoiceItem.
        Item currency

        :param currency: The currency of this InvoiceItem.
        :type: str
        """

        self._currency = currency

    @property
    def start_date(self):
        """
        Gets the start_date of this InvoiceItem.
        Begining of the time range

        :return: The start_date of this InvoiceItem.
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """
        Sets the start_date of this InvoiceItem.
        Begining of the time range

        :param start_date: The start_date of this InvoiceItem.
        :type: datetime
        """

        self._start_date = start_date

    @property
    def end_date(self):
        """
        Gets the end_date of this InvoiceItem.
        End of the time range

        :return: The end_date of this InvoiceItem.
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """
        Sets the end_date of this InvoiceItem.
        End of the time range

        :param end_date: The end_date of this InvoiceItem.
        :type: datetime
        """

        self._end_date = end_date

    @property
    def charge_type(self):
        """
        Gets the charge_type of this InvoiceItem.
        Type of charge  * RECURRING - Recurs every interval e.g. monthly  * ONE_TIME - A one-time charge delivered on starting date 

        :return: The charge_type of this InvoiceItem.
        :rtype: str
        """
        return self._charge_type

    @charge_type.setter
    def charge_type(self, charge_type):
        """
        Sets the charge_type of this InvoiceItem.
        Type of charge  * RECURRING - Recurs every interval e.g. monthly  * ONE_TIME - A one-time charge delivered on starting date 

        :param charge_type: The charge_type of this InvoiceItem.
        :type: str
        """
        allowed_values = ["RECURRING", "ONE-TIME"]
        if charge_type not in allowed_values:
            raise ValueError(
                "Invalid value for `charge_type` ({0}), must be one of {1}"
                .format(charge_type, allowed_values)
            )

        self._charge_type = charge_type

    @property
    def region(self):
        """
        Gets the region of this InvoiceItem.

        :return: The region of this InvoiceItem.
        :rtype: DocumentRegion
        """
        return self._region

    @region.setter
    def region(self, region):
        """
        Sets the region of this InvoiceItem.

        :param region: The region of this InvoiceItem.
        :type: DocumentRegion
        """

        self._region = region

    @property
    def inventory_id(self):
        """
        Gets the inventory_id of this InvoiceItem.
        Id of an inventory description

        :return: The inventory_id of this InvoiceItem.
        :rtype: str
        """
        return self._inventory_id

    @inventory_id.setter
    def inventory_id(self, inventory_id):
        """
        Sets the inventory_id of this InvoiceItem.
        Id of an inventory description

        :param inventory_id: The inventory_id of this InvoiceItem.
        :type: str
        """

        self._inventory_id = inventory_id

    @property
    def inventory_type(self):
        """
        Gets the inventory_type of this InvoiceItem.

        :return: The inventory_type of this InvoiceItem.
        :rtype: str
        """
        return self._inventory_type

    @inventory_type.setter
    def inventory_type(self, inventory_type):
        """
        Sets the inventory_type of this InvoiceItem.

        :param inventory_type: The inventory_type of this InvoiceItem.
        :type: str
        """
        allowed_values = ["HOST"]
        if inventory_type not in allowed_values:
            raise ValueError(
                "Invalid value for `inventory_type` ({0}), must be one of {1}"
                .format(inventory_type, allowed_values)
            )

        self._inventory_type = inventory_type

    @property
    def tags(self):
        """
        Gets the tags of this InvoiceItem.

        :return: The tags of this InvoiceItem.
        :rtype: TagSet
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """
        Sets the tags of this InvoiceItem.

        :param tags: The tags of this InvoiceItem.
        :type: TagSet
        """

        self._tags = tags

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InvoiceItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
