# coding: utf-8

"""
    Goldfin Service Admin API

    REST API for Goldfin Service Administration

    OpenAPI spec version: 1.0.0
    Contact: info@goldfin.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InvoiceParameters(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'tags': 'str'
    }

    attribute_map = {
        'description': 'description',
        'tags': 'tags'
    }

    def __init__(self, description=None, tags=None):
        """
        InvoiceParameters - a model defined in Swagger
        """

        self._description = None
        self._tags = None

        if description is not None:
          self.description = description
        if tags is not None:
          self.tags = tags

    @property
    def description(self):
        """
        Gets the description of this InvoiceParameters.
        A user-provided description of the invoice

        :return: The description of this InvoiceParameters.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this InvoiceParameters.
        A user-provided description of the invoice

        :param description: The description of this InvoiceParameters.
        :type: str
        """

        self._description = description

    @property
    def tags(self):
        """
        Gets the tags of this InvoiceParameters.
        A user-provided list of name-value pairs that describe the invoice

        :return: The tags of this InvoiceParameters.
        :rtype: str
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """
        Sets the tags of this InvoiceParameters.
        A user-provided list of name-value pairs that describe the invoice

        :param tags: The tags of this InvoiceParameters.
        :type: str
        """

        self._tags = tags

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InvoiceParameters):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
