# coding: utf-8

"""
    Goldfin Service API

    REST API for Goldfin Intelligent Invoice Processing

    OpenAPI spec version: 1.0.0
    Contact: info@goldfin.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class User(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'tenant_id': 'str',
        'username': 'str',
        'roles': 'str',
        'creation_date': 'str'
    }

    attribute_map = {
        'id': 'id',
        'tenant_id': 'tenantId',
        'username': 'username',
        'roles': 'roles',
        'creation_date': 'creationDate'
    }

    def __init__(self, id=None, tenant_id=None, username=None, roles=None, creation_date=None):
        """
        User - a model defined in Swagger
        """

        self._id = None
        self._tenant_id = None
        self._username = None
        self._roles = None
        self._creation_date = None

        if id is not None:
          self.id = id
        if tenant_id is not None:
          self.tenant_id = tenant_id
        if username is not None:
          self.username = username
        if roles is not None:
          self.roles = roles
        if creation_date is not None:
          self.creation_date = creation_date

    @property
    def id(self):
        """
        Gets the id of this User.
        Unique user id

        :return: The id of this User.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this User.
        Unique user id

        :param id: The id of this User.
        :type: str
        """

        self._id = id

    @property
    def tenant_id(self):
        """
        Gets the tenant_id of this User.
        Tenant ID

        :return: The tenant_id of this User.
        :rtype: str
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """
        Sets the tenant_id of this User.
        Tenant ID

        :param tenant_id: The tenant_id of this User.
        :type: str
        """

        self._tenant_id = tenant_id

    @property
    def username(self):
        """
        Gets the username of this User.
        Unique user name

        :return: The username of this User.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """
        Sets the username of this User.
        Unique user name

        :param username: The username of this User.
        :type: str
        """

        self._username = username

    @property
    def roles(self):
        """
        Gets the roles of this User.
        Comma-separated list of user roles

        :return: The roles of this User.
        :rtype: str
        """
        return self._roles

    @roles.setter
    def roles(self, roles):
        """
        Sets the roles of this User.
        Comma-separated list of user roles

        :param roles: The roles of this User.
        :type: str
        """

        self._roles = roles

    @property
    def creation_date(self):
        """
        Gets the creation_date of this User.
        Date user record was created

        :return: The creation_date of this User.
        :rtype: str
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date):
        """
        Sets the creation_date of this User.
        Date user record was created

        :param creation_date: The creation_date of this User.
        :type: str
        """

        self._creation_date = creation_date

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, User):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
