# coding: utf-8

"""
    Goldfin Service API

    REST API for Goldfin Intelligent Invoice Processing

    OpenAPI spec version: 1.0.0
    Contact: info@goldfin.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Vendor(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'identifier': 'str',
        'name': 'str',
        'state': 'str',
        'tags': 'TagSet',
        'creation_date': 'str'
    }

    attribute_map = {
        'id': 'id',
        'identifier': 'identifier',
        'name': 'name',
        'state': 'state',
        'tags': 'tags',
        'creation_date': 'creationDate'
    }

    def __init__(self, id=None, identifier=None, name=None, state=None, tags=None, creation_date=None):
        """
        Vendor - a model defined in Swagger
        """

        self._id = None
        self._identifier = None
        self._name = None
        self._state = None
        self._tags = None
        self._creation_date = None

        if id is not None:
          self.id = id
        if identifier is not None:
          self.identifier = identifier
        if name is not None:
          self.name = name
        if state is not None:
          self.state = state
        if tags is not None:
          self.tags = tags
        if creation_date is not None:
          self.creation_date = creation_date

    @property
    def id(self):
        """
        Gets the id of this Vendor.
        Unique vendor id

        :return: The id of this Vendor.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Vendor.
        Unique vendor id

        :param id: The id of this Vendor.
        :type: str
        """

        self._id = id

    @property
    def identifier(self):
        """
        Gets the identifier of this Vendor.
        Standard key used to describe vendor for accounting purposes

        :return: The identifier of this Vendor.
        :rtype: str
        """
        return self._identifier

    @identifier.setter
    def identifier(self, identifier):
        """
        Sets the identifier of this Vendor.
        Standard key used to describe vendor for accounting purposes

        :param identifier: The identifier of this Vendor.
        :type: str
        """

        self._identifier = identifier

    @property
    def name(self):
        """
        Gets the name of this Vendor.
        Vendor display name

        :return: The name of this Vendor.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Vendor.
        Vendor display name

        :param name: The name of this Vendor.
        :type: str
        """

        self._name = name

    @property
    def state(self):
        """
        Gets the state of this Vendor.
        Current state of the vendor.  Active vendors have current inventory and invoices.

        :return: The state of this Vendor.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """
        Sets the state of this Vendor.
        Current state of the vendor.  Active vendors have current inventory and invoices.

        :param state: The state of this Vendor.
        :type: str
        """
        allowed_values = ["ACTIVE", "INACTIVE"]
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def tags(self):
        """
        Gets the tags of this Vendor.

        :return: The tags of this Vendor.
        :rtype: TagSet
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """
        Sets the tags of this Vendor.

        :param tags: The tags of this Vendor.
        :type: TagSet
        """

        self._tags = tags

    @property
    def creation_date(self):
        """
        Gets the creation_date of this Vendor.
        Date record was created

        :return: The creation_date of this Vendor.
        :rtype: str
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date):
        """
        Sets the creation_date of this Vendor.
        Date record was created

        :param creation_date: The creation_date of this Vendor.
        :type: str
        """

        self._creation_date = creation_date

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Vendor):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
