/**
 * Goldfin Service API
 * REST API for Goldfin Intelligent Invoice Processing
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@goldfin.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * API key pair
 */
export interface ApiKey {
    /**
     * Unique API key ID
     */
    id?: string;
    /**
     * Name of this API key; must be unique among keys owned by a user.
     */
    name?: string;
    /**
     * User ID
     */
    userId?: string;
    /**
     * Secret password for the API key. This is only shown on initial creation; if lost a new API key must be created to replace it.
     */
    secret?: string;
    /**
     * Date of last use of key
     */
    lastTouchedDate?: Date;
}
