/**
 * Goldfin Service Admin API
 * REST API for Goldfin Service Administration
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@goldfin.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * User settable document parameters
 */
export interface DocumentParameters {
    /**
     * Name of the document
     */
    name?: string;

    /**
     * Optional description of the document
     */
    description?: string;

}
