/**
 * Goldfin Service API
 * REST API for Goldfin Intelligent Invoice Processing
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@goldfin.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TagSet } from './tagSet';


/**
 * A document, for example a PDF file containing an invoice
 */
export interface Document {
    /**
     * Document ID
     */
    id?: string;
    /**
     * Name of the document
     */
    name?: string;
    /**
     * Optional description of the document
     */
    description?: string;
    /**
     * Internet media type (e.g., application/octet-stream)
     */
    contentType?: string;
    /**
     * Document length in bytes
     */
    contentLength?: number;
    /**
     * SHA-256 thumbprint of document content
     */
    thumbprint?: string;
    /**
     * Storage locator of the document
     */
    locator?: string;
    /**
     * The current processing state of the document.  The document type and content ID are available after scanning
     */
    state?: Document.StateEnum;
    /**
     * Kind of document, e.g., an invoice.
     */
    semanticType?: Document.SemanticTypeEnum;
    /**
     * ID of the document's scanned content, e.g. an invoice ID
     */
    semanticId?: string;
    tags?: TagSet;
    /**
     * Date document was uploaded
     */
    creationDate?: string;
}
export namespace Document {
    export type StateEnum = 'CREATED' | 'SCAN_REQUESTED' | 'SCANNED' | 'ERROR';
    export const StateEnum = {
        CREATED: 'CREATED' as StateEnum,
        SCANREQUESTED: 'SCAN_REQUESTED' as StateEnum,
        SCANNED: 'SCANNED' as StateEnum,
        ERROR: 'ERROR' as StateEnum
    }
    export type SemanticTypeEnum = 'INVOICE' | 'UNKNOWN';
    export const SemanticTypeEnum = {
        INVOICE: 'INVOICE' as SemanticTypeEnum,
        UNKNOWN: 'UNKNOWN' as SemanticTypeEnum
    }
}
