/**
 * Goldfin Service API
 * REST API for Goldfin Intelligent Invoice Processing
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@goldfin.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * An validation result that checks a specific invoice rule
 */
export interface InvoiceValidationResult {
    /**
     * A concise summary of the check
     */
    summary?: string;

    /**
     * If true the check passed
     */
    passed?: boolean;

    /**
     * The type of validation, which can be related to the invoice itself or an invoice line item.  In the latter case line item fields are included; otherwise line item information is omitted.
     */
    validationType?: InvoiceValidationResult.ValidationTypeEnum;

    /**
     * Detailed information about the exception
     */
    details?: string;

    /**
     * ID of invoice to which discrepancy applies
     */
    invoiceId?: string;

    /**
     * Invoice identifier
     */
    identifier?: string;

    /**
     * Invoice effective date
     */
    effectiveDate?: Date;

    /**
     * Vendor identifier
     */
    vendorIdentifier?: string;

    /**
     * Invoice line item ID
     */
    invoiceItemId?: string;

    /**
     * Invoice line item inventory resource ID
     */
    invoiceItemResourceId?: string;

}
export namespace InvoiceValidationResult {
    export enum ValidationTypeEnum {
        INVOICE = <any> 'INVOICE',
        INVOICELINEITEM = <any> 'INVOICE_LINE_ITEM'
    }
}
