/**
 * Goldfin Service Admin API
 * REST API for Goldfin Service Administration
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@goldfin.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * User settable invoice parameters
 */
export interface InvoiceParameters {
    /**
     * A user-provided description of the invoice
     */
    description?: string;

    /**
     * A user-provided list of name-value pairs that describe the invoice
     */
    tags?: string;

}
