/**
 * Goldfin Service API
 * REST API for Goldfin Intelligent Invoice Processing
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@goldfin.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InvoiceItem } from './invoiceItem';
import { TagSet } from './tagSet';


/**
 * Invoice content obtained from document scanning
 */
export interface Invoice {
    /**
     * Invoice ID
     */
    id?: string;
    /**
     * Source document ID
     */
    documentId?: string;
    /**
     * A user-provided description of the invoice
     */
    description?: string;
    /**
     * Invoice identifier
     */
    identifier?: string;
    /**
     * Account to which invoice applies
     */
    account?: string;
    /**
     * Invoice effective date
     */
    effectiveDate?: Date;
    /**
     * Vendor identifier
     */
    vendorIdentifier?: string;
    /**
     * Invoice subtotal amount
     */
    subtotalAmount?: number;
    /**
     * Invoice total credits
     */
    credit?: number;
    /**
     * Invoice tax amount
     */
    tax?: number;
    /**
     * Invoice total (subtotal + tax)
     */
    totalAmount?: number;
    /**
     * Currency type
     */
    currency?: string;
    /**
     * Invoice items
     */
    items?: Array<InvoiceItem>;
    tags?: TagSet;
    /**
     * Date user record was created
     */
    creationDate?: string;
}
