/**
 * Goldfin Service API
 * REST API for Goldfin Intelligent Invoice Processing
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@goldfin.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Parameters for creating or updating a user account
 */
export interface UserParameters {
    /**
     * Unique user name in form 'username@tenantname'
     */
    user?: string;

    /**
     * Initial user password; ignored after creation
     */
    initialPassword?: string;

    /**
     * Comma-separated list of user roles
     */
    roles?: string;

}
