/**
 * Goldfin Service API
 * REST API for Goldfin Intelligent Invoice Processing
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@goldfin.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Key describing a specific validation type
 */
export type ValidationType = 'INVOICE' | 'INVOICE_LINE_ITEM';

export const ValidationType = {
    INVOICE: 'INVOICE' as ValidationType,
    INVOICELINEITEM: 'INVOICE_LINE_ITEM' as ValidationType
}
