/**
 * Goldfin Service API
 * REST API for Goldfin Intelligent Invoice Processing
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@goldfin.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Parameters used for vendor creation or update requests
 */
export interface VendorParameters {
    /**
     * Key used to describe vendor for accounting purposes
     */
    identifier?: string;

    /**
     * Vendor name
     */
    name?: string;

    /**
     * Current state of the vendor.  Active vendors have current inventory and invoices.
     */
    state?: VendorParameters.StateEnum;

}
export namespace VendorParameters {
    export enum StateEnum {
        ACTIVE = <any> 'ACTIVE',
        INACTIVE = <any> 'INACTIVE'
    }
}
