/**
 * Goldfin Service API
 * REST API for Goldfin Intelligent Invoice Processing
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@goldfin.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TagSet } from './tagSet';


/**
 * Vendor description
 */
export interface Vendor {
    /**
     * Unique vendor id
     */
    id?: string;
    /**
     * Standard key used to describe vendor for accounting purposes
     */
    identifier?: string;
    /**
     * Vendor display name
     */
    name?: string;
    /**
     * Current state of the vendor.  Active vendors have current inventory and invoices.
     */
    state?: Vendor.StateEnum;
    tags?: TagSet;
    /**
     * Date record was created
     */
    creationDate?: string;
}
export namespace Vendor {
    export type StateEnum = 'ACTIVE' | 'INACTIVE';
    export const StateEnum = {
        ACTIVE: 'ACTIVE' as StateEnum,
        INACTIVE: 'INACTIVE' as StateEnum
    }
}
