/**
 * Goldfin Service API
 * REST API for Goldfin Intelligent Invoice Processing
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@goldfin.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { ApiResponse } from '../model/apiResponse';
import { Tenant } from '../model/tenant';
import { TenantParameters } from '../model/tenantParameters';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class TenantService {

    protected basePath = 'https://api.goldfin.io/api/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Create a new tenant
     * Upload a new tenant registration request.
     * @param body Tenant creation parameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public tenantCreate(body: TenantParameters, observe?: 'body', reportProgress?: boolean): Observable<Tenant>;
    public tenantCreate(body: TenantParameters, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Tenant>>;
    public tenantCreate(body: TenantParameters, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Tenant>>;
    public tenantCreate(body: TenantParameters, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling tenantCreate.');
        }

        let headers = this.defaultHeaders;

        // authentication (ApiKey) required
        if (this.configuration.apiKeys["vnd.io.goldfin.apikey"]) {
            headers = headers.set('vnd.io.goldfin.apikey', this.configuration.apiKeys["vnd.io.goldfin.apikey"]);
        }

        // authentication (SessionKey) required
        if (this.configuration.apiKeys["vnd.io.goldfin.session"]) {
            headers = headers.set('vnd.io.goldfin.session', this.configuration.apiKeys["vnd.io.goldfin.session"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<Tenant>(`${this.basePath}/tenant`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete a tenant
     * Delete a single tenant
     * @param id Tenant ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public tenantDelete(id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public tenantDelete(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public tenantDelete(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public tenantDelete(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling tenantDelete.');
        }

        let headers = this.defaultHeaders;

        // authentication (ApiKey) required
        if (this.configuration.apiKeys["vnd.io.goldfin.apikey"]) {
            headers = headers.set('vnd.io.goldfin.apikey', this.configuration.apiKeys["vnd.io.goldfin.apikey"]);
        }

        // authentication (SessionKey) required
        if (this.configuration.apiKeys["vnd.io.goldfin.session"]) {
            headers = headers.set('vnd.io.goldfin.session', this.configuration.apiKeys["vnd.io.goldfin.session"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/tenant/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Show a single tenant
     * Return all information relative to a single tenant
     * @param id Tenant ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public tenantShow(id: string, observe?: 'body', reportProgress?: boolean): Observable<Tenant>;
    public tenantShow(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Tenant>>;
    public tenantShow(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Tenant>>;
    public tenantShow(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling tenantShow.');
        }

        let headers = this.defaultHeaders;

        // authentication (ApiKey) required
        if (this.configuration.apiKeys["vnd.io.goldfin.apikey"]) {
            headers = headers.set('vnd.io.goldfin.apikey', this.configuration.apiKeys["vnd.io.goldfin.apikey"]);
        }

        // authentication (SessionKey) required
        if (this.configuration.apiKeys["vnd.io.goldfin.session"]) {
            headers = headers.set('vnd.io.goldfin.session', this.configuration.apiKeys["vnd.io.goldfin.session"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Tenant>(`${this.basePath}/tenant/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List tenants
     * Return a list of all tenants
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public tenantShowall(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public tenantShowall(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public tenantShowall(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public tenantShowall(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (ApiKey) required
        if (this.configuration.apiKeys["vnd.io.goldfin.apikey"]) {
            headers = headers.set('vnd.io.goldfin.apikey', this.configuration.apiKeys["vnd.io.goldfin.apikey"]);
        }

        // authentication (SessionKey) required
        if (this.configuration.apiKeys["vnd.io.goldfin.session"]) {
            headers = headers.set('vnd.io.goldfin.session', this.configuration.apiKeys["vnd.io.goldfin.session"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/tenant`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update a tenant
     * Update invoice description and tags. Changes to other fields are ignored
     * @param id Tenant ID
     * @param body Tenant parameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public tenantUpdate(id: string, body?: TenantParameters, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public tenantUpdate(id: string, body?: TenantParameters, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public tenantUpdate(id: string, body?: TenantParameters, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public tenantUpdate(id: string, body?: TenantParameters, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling tenantUpdate.');
        }

        let headers = this.defaultHeaders;

        // authentication (ApiKey) required
        if (this.configuration.apiKeys["vnd.io.goldfin.apikey"]) {
            headers = headers.set('vnd.io.goldfin.apikey', this.configuration.apiKeys["vnd.io.goldfin.apikey"]);
        }

        // authentication (SessionKey) required
        if (this.configuration.apiKeys["vnd.io.goldfin.session"]) {
            headers = headers.set('vnd.io.goldfin.session', this.configuration.apiKeys["vnd.io.goldfin.session"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/tenant/${encodeURIComponent(String(id))}`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
