/**
 * Goldfin Service API
 * REST API for Goldfin Intelligent Invoice Processing
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@goldfin.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { ApiResponse } from '../model/apiResponse';
import { Vendor } from '../model/vendor';
import { VendorParameters } from '../model/vendorParameters';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class VendorService {

    protected basePath = 'https://api.goldfin.io/api/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Create a new vendor
     * Upload a new vendor definition.  Vendors are also created automatically if a vendor invoice is processed.
     * @param body Vendor registration request parameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public vendorCreate(body: VendorParameters, observe?: 'body', reportProgress?: boolean): Observable<Vendor>;
    public vendorCreate(body: VendorParameters, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Vendor>>;
    public vendorCreate(body: VendorParameters, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Vendor>>;
    public vendorCreate(body: VendorParameters, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling vendorCreate.');
        }

        let headers = this.defaultHeaders;

        // authentication (ApiKey) required
        if (this.configuration.apiKeys["vnd.io.goldfin.apikey"]) {
            headers = headers.set('vnd.io.goldfin.apikey', this.configuration.apiKeys["vnd.io.goldfin.apikey"]);
        }

        // authentication (SessionKey) required
        if (this.configuration.apiKeys["vnd.io.goldfin.session"]) {
            headers = headers.set('vnd.io.goldfin.session', this.configuration.apiKeys["vnd.io.goldfin.session"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<Vendor>(`${this.basePath}/vendor`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete a vendor
     * Delete a single vendor.  This can only be done if the vendor is not attached to invoices or existing inventory.
     * @param id vendor ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public vendorDelete(id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public vendorDelete(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public vendorDelete(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public vendorDelete(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling vendorDelete.');
        }

        let headers = this.defaultHeaders;

        // authentication (ApiKey) required
        if (this.configuration.apiKeys["vnd.io.goldfin.apikey"]) {
            headers = headers.set('vnd.io.goldfin.apikey', this.configuration.apiKeys["vnd.io.goldfin.apikey"]);
        }

        // authentication (SessionKey) required
        if (this.configuration.apiKeys["vnd.io.goldfin.session"]) {
            headers = headers.set('vnd.io.goldfin.session', this.configuration.apiKeys["vnd.io.goldfin.session"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/vendor/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Show a single vendor
     * Return all information relative to a single vendor
     * @param id Vendor ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public vendorShow(id: string, observe?: 'body', reportProgress?: boolean): Observable<Vendor>;
    public vendorShow(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Vendor>>;
    public vendorShow(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Vendor>>;
    public vendorShow(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling vendorShow.');
        }

        let headers = this.defaultHeaders;

        // authentication (ApiKey) required
        if (this.configuration.apiKeys["vnd.io.goldfin.apikey"]) {
            headers = headers.set('vnd.io.goldfin.apikey', this.configuration.apiKeys["vnd.io.goldfin.apikey"]);
        }

        // authentication (SessionKey) required
        if (this.configuration.apiKeys["vnd.io.goldfin.session"]) {
            headers = headers.set('vnd.io.goldfin.session', this.configuration.apiKeys["vnd.io.goldfin.session"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Vendor>(`${this.basePath}/vendor/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List vendors
     * Return a list of all vendors
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public vendorShowall(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public vendorShowall(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public vendorShowall(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public vendorShowall(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (ApiKey) required
        if (this.configuration.apiKeys["vnd.io.goldfin.apikey"]) {
            headers = headers.set('vnd.io.goldfin.apikey', this.configuration.apiKeys["vnd.io.goldfin.apikey"]);
        }

        // authentication (SessionKey) required
        if (this.configuration.apiKeys["vnd.io.goldfin.session"]) {
            headers = headers.set('vnd.io.goldfin.session', this.configuration.apiKeys["vnd.io.goldfin.session"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/vendor`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update a vendor
     * Update vendor description.
     * @param id Vendor ID
     * @param body Vendor parameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public vendorUpdate(id: string, body?: VendorParameters, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public vendorUpdate(id: string, body?: VendorParameters, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public vendorUpdate(id: string, body?: VendorParameters, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public vendorUpdate(id: string, body?: VendorParameters, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling vendorUpdate.');
        }

        let headers = this.defaultHeaders;

        // authentication (ApiKey) required
        if (this.configuration.apiKeys["vnd.io.goldfin.apikey"]) {
            headers = headers.set('vnd.io.goldfin.apikey', this.configuration.apiKeys["vnd.io.goldfin.apikey"]);
        }

        // authentication (SessionKey) required
        if (this.configuration.apiKeys["vnd.io.goldfin.session"]) {
            headers = headers.set('vnd.io.goldfin.session', this.configuration.apiKeys["vnd.io.goldfin.session"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/vendor/${encodeURIComponent(String(id))}`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
