# coding: utf-8

"""
    Goldfin Storage API

    REST API for Goldfin Storage Microservice

    OpenAPI spec version: 1.0.0
    Contact: info@goldfin.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .api_response import ApiResponse
from .document import Document
from .tenant_info import TenantInfo
